# Use Kaniko to build on containers without root, ie on Kubernetes

image:
  name: registry.heimsbakk.no:5487/docker/executor:debug
  entrypoint: [""]

variables:
  VERSION: latest

before_script:
  - sed -i "s/VERSION/${VERSION}/g" Dockerfile

# Check if we build successfully on all branches.

test:
  stage: test
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push
  except:
    - master

# Build container and push to registry for master branch.

build:
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$VERSION
  only:
    - master

